# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Implement a random walk Metropolis sampler.
#' @description Implement a random walk Metropolis sampler for generating the standard Laplace distribution.
#' @param mu The mean of Laplace distribution.
#' @param lambda The lambda parameter of Laplace distribution.
#' @param sigma The standard deviation of the norm target distribution.
#' @param x0 The initial value of a random walk sequence.
#' @param N The length of a random walk sequence.
#' @return a random walk sequence and the number of times it was accepted.
#' @examples
#' \dontrun{
#' set.seed(1234)
#' mu=0;lambda=1;sigma=1
#' x0=10
#' N=15000
#' rw<- rwMetropolisC(mu,lambda, sigma, x0, N)
#' }
#' @useDynLib StatComp20095
#' @export
rwMetropolisC <- function(mu, lambda, sigma, x0, N) {
    .Call('_StatComp20095_rwMetropolisC', PACKAGE = 'StatComp20095', mu, lambda, sigma, x0, N)
}

